services:
  pl_request_handler:
    build:
      context: ./sources
      dockerfile: ../configs/Dockerfile
      args:
        SERVICE_PATH: ${PL_REQUEST_HANDLER_BASE}
    container_name: ${PL_REQUEST_HANDLER_NAME}
    ports:
      - "${PL_REQUEST_HANDLER_PORT}:3000"
    volumes:
      - ./sources/${PL_REQUEST_HANDLER_BASE}:/usr/src/app
    command: npm run dev
    networks:
      - docker-network

  # Validator
  bs_validator:
    build:
      context: ./sources
      dockerfile: ../configs/Dockerfile
      args:
        SERVICE_PATH: ${VALIDATOR_BASE}
    container_name: ${VALIDATOR_NAME}
    ports:
      - "${VALIDATOR_PORT}:3000"
    volumes:
      - ./sources/${VALIDATOR_BASE}:/usr/src/app
    command: npx ts-node -r tsconfig-paths/register src/entrypoints/queueConsumer.ts
    networks:
      - docker-network

  # Vendors
  vendor_gde:
    build:
      context: ./sources
      dockerfile: ../configs/Dockerfile
      args:
        SERVICE_PATH: ${VENDOR_GDE_BASE}
    container_name: ${VENDOR_GDE_NAME}
    ports:
      - "${VENDOR_GDE_PORT}:3000"
    volumes:
      - ./sources/${VENDOR_GDE_BASE}:/usr/src/app
    command: npx ts-node -r tsconfig-paths/register src/entrypoints/queueConsumer.ts
    networks:
      - docker-network

networks:
  docker-network:
    name: ${GLOBAL_NETWORK_NAME}
    external: true